name: NuGet Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: 8.0.x
      
      - name: Install Mono
        run: |
          sudo apt update
          sudo apt install -y mono-complete
          
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2.0.1
        with:
          nuget-version: '6.x'
      
      - name: Pack NuGet package
        run: |
          cd Exiled_Dev_References
          mono $(which nuget) pack Exiled_Dev_References.nuspec -OutputDirectory ../nupkg
        
      - name: Push to NuGet
        if: github.event_name != 'pull_request'
        run: |
          dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate