name: NuGet Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.2.2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: 8.0.x
      
      - name: Configure NuGet for GitHub Packages
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/Swishhyy/index.json" --name "github" --username Swishhyy --password ${{ secrets.PUBLISHING_KEY }}
      
      - name: Build and Pack NuGet Package
        run: |
          dotnet build -c Release Exiled.Dev.References/Exiled.Dev.References.csproj
          dotnet pack -c Release Exiled.Dev.References/Exiled.Dev.References.csproj --output ./nupkg
        
      - name: Push to NuGet
        if: github.event_name != 'pull_request'
        run: |
          dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
          
      - name: Push to GitHub Packages
        if: github.event_name != 'pull_request'
        run: |
          dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.PUBLISHING_KEY }} --source "github" --skip-duplicate