name: NuGet Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: 8.0.x
      
      - name: Create temporary project file
        run: |
          cd Exiled_Dev_References
          cat > Exiled_Dev_References.csproj << EOF
          <Project Sdk="Microsoft.NET.Sdk">
            <PropertyGroup>
              <TargetFramework>net45</TargetFramework>
              <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
              <NuspecFile>Exiled_Dev_References.nuspec</NuspecFile>
              <PackageOutputPath>../nupkg</PackageOutputPath>
            </PropertyGroup>
          </Project>
          EOF
      
      - name: Pack using dotnet
        run: |
          cd Exiled_Dev_References
          dotnet pack -c Release
        
      - name: Push to NuGet
        if: github.event_name != 'pull_request'
        run: |
          dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate